
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import type { ReactNode } from "react";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";
import SignOutButton from "@/components/SignOutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProviderWrapper>
          <div className="p-4 flex justify-between items-center bg-gray-100">
            <h1 className="text-xl font-bold">Hospital Management</h1>
            <SignOutButton /> 
          </div>
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
